CREATE TABLE IF NOT EXISTS payments (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    order_id BIGINT NOT NULL REFERENCES orders (id) ON DELETE RESTRICT,
    user_id BIGINT NOT NULL REFERENCES users (id) ON DELETE RESTRICT,
    provider TEXT NOT NULL DEFAULT 'manual' CHECK (provider IN ('manual', 'alipay')),
    merchant_order_no TEXT NOT NULL UNIQUE,
    provider_trade_no TEXT NOT NULL DEFAULT '',
    amount_cents BIGINT NOT NULL CHECK (amount_cents >= 0),
    currency CHAR(3) NOT NULL DEFAULT 'CNY',
    status TEXT NOT NULL DEFAULT 'created' CHECK (
        status IN ('created', 'pending', 'succeeded', 'failed', 'cancelled', 'refunded')
    ),
    raw_payload JSONB NOT NULL DEFAULT '{}'::jsonb,
    paid_at TIMESTAMPTZ,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS payments_order_id_idx ON payments (order_id);
CREATE INDEX IF NOT EXISTS payments_user_id_created_at_idx ON payments (user_id, created_at DESC);
CREATE INDEX IF NOT EXISTS payments_status_idx ON payments (status);
